=== NCIP/CURE/FormBuilder/formbuilder-dataset.dtd
<!ELEMENT dataset (
   (answer|
    answer_skip_rule|
    answer_value|
    category|
    form|
    form_element|
    module|
    question|
    question_categries|
    question_orig|
    question_skip_rule|
    roles|
    rpt_users|
    skip_rule|
    user_roles)*)>

<!ELEMENT answer EMPTY>
<!ATTLIST answer
    id CDATA #REQUIRED
    type CDATA #REQUIRED
    description CDATA #IMPLIED
    group_name CDATA #IMPLIED
    question_id CDATA #REQUIRED
    ord CDATA #IMPLIED
    answer_column_heading CDATA #IMPLIED
    display_style CDATA #IMPLIED
    value_constraint CDATA #IMPLIED
    uuid CDATA #IMPLIED
>

<!ELEMENT answer_skip_rule EMPTY>
<!ATTLIST answer_skip_rule
    id CDATA #REQUIRED
    parent_id CDATA #REQUIRED
    answer_value_id CDATA #REQUIRED
    dtype CDATA #IMPLIED
    form_uuid CDATA #IMPLIED
    question_uuid CDATA #IMPLIED
    form_id CDATA #IMPLIED
>

<!ELEMENT answer_value EMPTY>
<!ATTLIST answer_value
    id CDATA #REQUIRED
    short_name CDATA #REQUIRED
    value CDATA #REQUIRED
    answer_id CDATA #REQUIRED
    description CDATA #IMPLIED
    ord CDATA #REQUIRED
    permanent_id CDATA #REQUIRED
    cadsr_public_id CDATA #IMPLIED
    external_id CDATA #IMPLIED
>

<!ELEMENT category EMPTY>
<!ATTLIST category
    id CDATA #REQUIRED
    name CDATA #REQUIRED
    description CDATA #IMPLIED
>

<!ELEMENT form EMPTY>
<!ATTLIST form
    id CDATA #REQUIRED
    sequence CDATA #IMPLIED
    location CDATA #IMPLIED
    system_id CDATA #IMPLIED
    version CDATA #IMPLIED
    type CDATA #IMPLIED
    name CDATA #REQUIRED
    module_id CDATA #REQUIRED
    ord CDATA #REQUIRED
    status CDATA #REQUIRED
    update_date CDATA #REQUIRED
    author_user_id CDATA #REQUIRED
    uuid CDATA #REQUIRED
    locked_by_user_id CDATA #IMPLIED
    last_updated_by_user_id CDATA #IMPLIED
    form_type CDATA #IMPLIED
>

<!ELEMENT form_element EMPTY>
<!ATTLIST form_element
    id CDATA #REQUIRED
    description CDATA #IMPLIED
    form_id CDATA #IMPLIED
    ord CDATA #IMPLIED
    learn_more CDATA #IMPLIED
    is_required CDATA #IMPLIED
    uuid CDATA #IMPLIED
    link_id CDATA #IMPLIED
    link_source CDATA #IMPLIED
    is_visible CDATA #IMPLIED
    element_type CDATA #IMPLIED
    has_been_modified CDATA #IMPLIED
    answer_type CDATA #IMPLIED
    external_id CDATA #IMPLIED
    external_uuid CDATA #IMPLIED
    table_type CDATA #IMPLIED
>

<!ELEMENT module EMPTY>
<!ATTLIST module
    id CDATA #REQUIRED
    description CDATA #IMPLIED
    release_date CDATA #IMPLIED
    comments CDATA #IMPLIED
    update_date CDATA #REQUIRED
    author_user_id CDATA #REQUIRED
    status CDATA #REQUIRED
    is_library CDATA #IMPLIED
    module_type CDATA #IMPLIED
    completiontime CDATA #IMPLIED
>

<!ELEMENT question EMPTY>
<!ATTLIST question
    id CDATA #REQUIRED
    uuid CDATA #REQUIRED
    short_name CDATA #IMPLIED
    parent_id CDATA #REQUIRED
    ord CDATA #IMPLIED
    description CDATA #IMPLIED
    question_type CDATA #IMPLIED
    type CDATA #IMPLIED
    is_identifying CDATA #IMPLIED
>

<!ELEMENT question_categries EMPTY>
<!ATTLIST question_categries
    category_id CDATA #REQUIRED
    question_id CDATA #REQUIRED
>

<!ELEMENT question_orig EMPTY>
<!ATTLIST question_orig
    id CDATA #REQUIRED
    type CDATA #REQUIRED
    description CDATA #REQUIRED
    form_id CDATA #REQUIRED
    short_name CDATA #IMPLIED
    ord CDATA #REQUIRED
    learn_more CDATA #IMPLIED
    is_required CDATA #IMPLIED
    uuid CDATA #REQUIRED
    link_id CDATA #IMPLIED
    link_source CDATA #IMPLIED
    cadsr_public_id CDATA #IMPLIED
    is_visible CDATA #REQUIRED
    table_id CDATA #IMPLIED
    question_type CDATA #IMPLIED
    parent_id CDATA #IMPLIED
    parent_type CDATA #IMPLIED
>

<!ELEMENT question_skip_rule EMPTY>
<!ATTLIST question_skip_rule
    id CDATA #REQUIRED
    parent_id CDATA #REQUIRED
    rule_value CDATA #REQUIRED
    logical_op CDATA #IMPLIED
    identifying_answer_value_id CDATA #IMPLIED
>

<!ELEMENT roles EMPTY>
<!ATTLIST roles
    id CDATA #REQUIRED
    name CDATA #IMPLIED
>

<!ELEMENT rpt_users EMPTY>
<!ATTLIST rpt_users
    id CDATA #REQUIRED
    username CDATA #IMPLIED
    password CDATA #IMPLIED
    created_date CDATA #IMPLIED
    email_addr CDATA #IMPLIED
>

<!ELEMENT skip_rule EMPTY>
<!ATTLIST skip_rule
    id CDATA #REQUIRED
    parent_id CDATA #REQUIRED
    logical_op CDATA #IMPLIED
    parent_type CDATA #IMPLIED
>

<!ELEMENT user_roles EMPTY>
<!ATTLIST user_roles
    user_id CDATA #REQUIRED
    role_id CDATA #REQUIRED
>

=== NCIP/CURE/FormBuilder/src/test/resources/com/healthcit/cacure/businessdelegates/FormManagerIntegrationTest.xml
<!--
  Copyright (C) 2013 HealthCare IT, Inc. - All Rights Reserved
  Unauthorized copying or redistribution of this file in source and binary forms via any medium is strictly prohibited
  Proprietary and confidential
-->
<!DOCTYPE dataset SYSTEM "formbuilder-dataset.dtd">
<dataset>
    <module id="10" 
   		description="module description"
   		is_library="false"
   		status="IN_PROGRESS"
   		author_user_id="1"
   		update_date="2011-06-01 10:43"
        module_type="module"/>	
            
    <form id="11"
    	author_user_id="2"
    	module_id="10"
    	name="questionnaire form 1"
    	ord="1"
    	status="IN_REVIEW"
    	update_date="2011-07-01 11:00"
    	uuid="uuid-form-11"
    	form_type="questionnaireForm"
    	locked_by_user_id="1"
    	last_updated_by_user_id="1"
    />
    
    <form id="111"
    	author_user_id="1"
    	module_id="10"
    	name="questionnaire form 2"
    	ord="2"
    	status="IN_PROGRESS"
    	update_date="2011-07-11 12:00"
    	uuid="uuid-form-111"
    	form_type="questionnaireForm"
    	locked_by_user_id="2"
    	last_updated_by_user_id="1"
    />
     
    <module id="12" 
   		description="question library module description"
   		is_library="true"
   		status="QUESTION_LIBRARY"
   		author_user_id="2"
   		update_date="2011-10-02 11:10"
        module_type="questionLibrary"/>
        
    <form id="13"
    	author_user_id="1"
    	module_id="12"
    	name="question library form 1"
    	ord="1"
    	status="QUESTION_LIBRARY"
    	update_date="2011-08-02 12:00"
    	uuid="uuid-form-13"
    	form_type="questionLibraryForm"
    />
      
    <module id="14" 
   		description="form library module description"
   		is_library="true"
   		status="FORM_LIBRARY"
   		author_user_id="1"
   		update_date="2011-03-02 01:10"
        module_type="formLibrary"/>
        
    <form id="15"
    	author_user_id="1"
    	module_id="14"
    	name="form library form 1"
    	ord="1"
    	status="FORM_LIBRARY"
    	update_date="2011-03-18 10:10"
    	uuid="uuid-form-15"
    	form_type="questionLibraryForm"
    />  
</dataset>

=== NCIP/CURE/FormBuilder/src/test/resources/users_roles_dataset.xml
<!--
  Copyright (C) 2013 HealthCare IT, Inc. - All Rights Reserved
  Unauthorized copying or redistribution of this file in source and binary forms via any medium is strictly prohibited
  Proprietary and confidential
-->
<!DOCTYPE dataset SYSTEM "formbuilder-dataset.dtd">
<dataset>
	<roles
		id="10"
		name="ROLE_AUTHOR" />
	<roles
		id="20"
		name="ROLE_DEPLOYER" />
	<roles
		id="30"
		name="ROLE_APPROVER" />
	<roles
		id="40"
		name="ROLE_LIBRARIAN" />
	<roles
		id="999"
		name="ROLE_ADMIN" />
		
	<rpt_users
		id="1"
		username="lkagan"
		password="a564de63c2d0da68cf47586ee05984d7"
		created_date="2010-04-19"
		email_addr="lkagan@healthcit.com" />
		
	<user_roles
		user_id="1"
		role_id="10" />
	<user_roles
		user_id="1"
		role_id="999" />
	<user_roles
		user_id="1"
		role_id="20" />
		
	<rpt_users
		id="2"
		username="test"
		password="9ddc44f3f7f78da5781d6cab571b2fc5"
		created_date="2010-04-19" />
		
	<rpt_users
		id="3"
		username="dolson"
		password="65d15fe9156f9c4bbffd98085992a44e"
		created_date="2010-04-29"
		email_addr="" />
	<user_roles
		user_id="3"
		role_id="10" />
		
	<rpt_users
		id="4"
		username="GuestUser"
		password="084e0343a0486ff05530df6c705c8bb4"
		created_date="2010-08-12"
		email_addr="howard.shang@duke.edu" />
	<user_roles
		user_id="4"
		role_id="999" />
		
	<rpt_users
		id="5"
		username="pgupta"
		password="a564de63c2d0da68cf47586ee05984d7"
		created_date="2010-04-29"
		email_addr="gupta@healthcit.com" />
	<user_roles
		user_id="5"
		role_id="10" />
		
</dataset>
